env:
  es6: true
parserOptions:
  ecmaVersion: 2018
plugins:
  - node
  - jsdoc
  - prettier
  - security
extends:
  - "eslint:recommended"
  - "plugin:node/recommended"
  - "plugin:jsdoc/recommended"
  - "plugin:prettier/recommended"
  - "plugin:security/recommended"
globals:
  xrequire: readonly
  sxrequire: readonly
