env:
  es6: true
parserOptions:
  ecmaVersion: 2018
plugins:
  - node
  - security
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'plugin:security/recommended'
globals:
  xrequire: readonly
  sxrequire: readonly
