plugins:
  - security
extends:
  - 'mudamuda/node' # superior rule set
globals:
  xrequire: readonly
  global.basedir: readonly
  oldLog: readonly
  print: readonly
  PrintHistory: readonly
  platform: readonly
  isLinux: readonly
  isWindows: readonly
